# Generated by Django 4.2.5 on 2023-10-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='category',
            field=models.CharField(choices=[('TN', 'Танки'), ('HL', 'Хилы'), ('DD', 'ДД'), ('TR', 'Торговцы'), ('GM', 'Гилдмастеры'), ('QG', 'Квестгиверы'), ('BS', 'Кузнецы'), ('LW', 'Кожевники'), ('AL', 'Зельевары'), ('SC', 'Мастера заклинаний')], default='TN', max_length=2),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
