# Generated by Django 4.2.5 on 2023-10-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_alter_advertisement_category_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='attached_file',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
    ]
