# Generated by Django 4.2.5 on 2023-10-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_advertisement_attached_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
